import type { GenerationErrorClass } from "./classes.js";

export const PROVIDER_ERROR_MAP = {
  MINIMAX_API_KEY_MISSING: "AUTH_INVALID",
  MINIMAX_AUTH_FAILED: "AUTH_INVALID",
  MINIMAX_BAD_REQUEST: "CAPABILITY_UNSUPPORTED",
  MINIMAX_IMAGE_DOWNLOAD_FAILED: "NETWORK_FAILURE",
  MINIMAX_IMAGE_DOWNLOAD_TOO_LARGE: "CAPABILITY_UNSUPPORTED",
  MINIMAX_IMAGE_INVALID: "INTERNAL_STATE_ERROR",
  MINIMAX_INSUFFICIENT_BALANCE: "BILLING_REQUIRED",
  MINIMAX_MODEL_REQUIRES_REFERENCE: "CAPABILITY_UNSUPPORTED",
  MINIMAX_NETWORK_FAILED: "NETWORK_FAILURE",
  MINIMAX_NO_IMAGE: "INTERNAL_STATE_ERROR",
  MINIMAX_RATE_LIMITED: "RATE_LIMITED",
  MINIMAX_REF_TOO_MANY: "CAPABILITY_UNSUPPORTED",
  MINIMAX_SAFETY_BLOCKED: "CONTENT_REJECTED",
  MINIMAX_UPSTREAM_ERROR: "NETWORK_FAILURE",

  GEMINI_API_BAD_REQUEST: "CAPABILITY_UNSUPPORTED",
  GEMINI_API_KEY_MISSING: "AUTH_INVALID",
  GEMINI_API_NETWORK_FAILED: "NETWORK_FAILURE",
  GEMINI_API_NO_IMAGE: "INTERNAL_STATE_ERROR",
  GEMINI_API_RATE_LIMITED: "RATE_LIMITED",
  GEMINI_API_SAFETY_BLOCKED: "CONTENT_REJECTED",
  GEMINI_API_UPSTREAM_ERROR: "NETWORK_FAILURE",

  GROK_AUTH_FAILED: "AUTH_INVALID",
  GROK_BAD_REQUEST: "CAPABILITY_UNSUPPORTED",
  GROK_EMPTY_RESPONSE: "INTERNAL_STATE_ERROR",
  GROK_IMAGE_DOWNLOAD_FAILED: "NETWORK_FAILURE",
  GROK_IMAGE_TIMEOUT: "PROVIDER_TIMEOUT",
  GROK_NETWORK_FAILED: "NETWORK_FAILURE",
  GROK_PLANNER_BAD_REQUEST: "CAPABILITY_UNSUPPORTED",
  GROK_PLANNER_EMPTY_TOOL_CALL: "INTERNAL_STATE_ERROR",
  GROK_PLANNER_INVALID_TOOL_ARGS: "INTERNAL_STATE_ERROR",
  GROK_PLANNER_NETWORK_FAILED: "NETWORK_FAILURE",
  GROK_PLANNER_TIMEOUT: "PROVIDER_TIMEOUT",
  GROK_RATE_LIMITED: "RATE_LIMITED",
  GROK_SEARCH_BAD_REQUEST: "CAPABILITY_UNSUPPORTED",
  GROK_SEARCH_EMPTY_RESPONSE: "INTERNAL_STATE_ERROR",
  GROK_SEARCH_NETWORK_FAILED: "NETWORK_FAILURE",
  GROK_SEARCH_TIMEOUT: "PROVIDER_TIMEOUT",
  GROK_UPSTREAM_ERROR: "NETWORK_FAILURE",
  GROK_VIDEO_DOWNLOAD_FAILED: "NETWORK_FAILURE",
  GROK_VIDEO_EMPTY_RESPONSE: "INTERNAL_STATE_ERROR",
  GROK_VIDEO_EXPIRED: "MODEL_UNAVAILABLE",
  GROK_VIDEO_FAILED: "INTERNAL_STATE_ERROR",
  GROK_VIDEO_INVALID_MODE: "CAPABILITY_UNSUPPORTED",
  GROK_VIDEO_MODERATION_BLOCKED: "CONTENT_REJECTED",
  GROK_VIDEO_POLL_FAILED: "NETWORK_FAILURE",
  GROK_VIDEO_REF_TOO_MANY: "CAPABILITY_UNSUPPORTED",
  GROK_VIDEO_REQUEST_FAILED: "CAPABILITY_UNSUPPORTED",
  GROK_VIDEO_TIMEOUT: "PROVIDER_TIMEOUT",

  AGY_ARTIFACT_NOT_FOUND: "INTERNAL_STATE_ERROR",
  AGY_GENERATION_FAILED: "INTERNAL_STATE_ERROR",
  AGY_MALFORMED_RESULT: "INTERNAL_STATE_ERROR",
  AGY_PARSE_FAILED: "INTERNAL_STATE_ERROR",
  AGY_PATH_REJECTED: "INTERNAL_STATE_ERROR",
  AGY_PROCESS_ERROR: "NETWORK_FAILURE",
  AGY_QUOTA_EXHAUSTED: "RATE_LIMITED",
  AGY_TIMEOUT: "PROVIDER_TIMEOUT",

  ATLASCLOUD_API_KEY_MISSING: "AUTH_INVALID",
  ATLASCLOUD_GENERATE_FAILED: "NETWORK_FAILURE",
  ATLASCLOUD_GENERATION_FAILED: "INTERNAL_STATE_ERROR",
  ATLASCLOUD_NO_PREDICTION_ID: "INTERNAL_STATE_ERROR",
  ATLASCLOUD_OUTPUT_DOWNLOAD_FAILED: "NETWORK_FAILURE",
  ATLASCLOUD_REF_TOO_MANY: "CAPABILITY_UNSUPPORTED",
  ATLASCLOUD_UPLOAD_FAILED: "NETWORK_FAILURE",
  ATLASCLOUD_UPLOAD_NO_URL: "INTERNAL_STATE_ERROR",
} as const satisfies Record<string, GenerationErrorClass>;

export type ProviderErrorCode = keyof typeof PROVIDER_ERROR_MAP;

export type DynamicProviderCodeSite = {
  file: string;
  prefixVariable: string;
  prefixDomain: readonly string[];
  suffix: string;
  expandedCodes: readonly ProviderErrorCode[];
};

export const DYNAMIC_PROVIDER_CODE_SITES = [{
  file: "lib/grokImageCore.ts",
  prefixVariable: "prefix",
  prefixDomain: ["GROK_SEARCH", "GROK_PLANNER"],
  suffix: "BAD_REQUEST",
  expandedCodes: ["GROK_SEARCH_BAD_REQUEST", "GROK_PLANNER_BAD_REQUEST"],
}] as const satisfies readonly DynamicProviderCodeSite[];

export function providerErrorClass(code: unknown): GenerationErrorClass | undefined {
  if (typeof code !== "string") return undefined;
  return (PROVIDER_ERROR_MAP as Record<string, GenerationErrorClass>)[code];
}
